"""add user_id

Revision ID: 39f2612f8455
Revises: 6c031f024ab1
Create Date: 2025-11-16 21:04:38.954644

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '39f2612f8455'
down_revision: Union[str, None] = '6c031f024ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_insights', sa.Column('raw_data', sa.Text(), nullable=True))
    op.alter_column('document_insights', 'risks',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('document_insights', 'recommendations',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.create_index(op.f('ix_document_insights_id'), 'document_insights', ['id'], unique=False)
    op.drop_constraint('document_insights_document_id_fkey', 'document_insights', type_='foreignkey')
    op.create_foreign_key(None, 'document_insights', 'documents', ['document_id'], ['id'])
    op.drop_column('document_insights', 'llm_raw_response')
    op.add_column('products', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('sales', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'sales', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('stock_movements', sa.Column('user_id', sa.BigInteger(), nullable=False))
    op.create_foreign_key(None, 'stock_movements', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'stock_movements', type_='foreignkey')
    op.drop_column('stock_movements', 'user_id')
    op.drop_constraint(None, 'sales', type_='foreignkey')
    op.drop_column('sales', 'user_id')
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.drop_column('products', 'user_id')
    op.add_column('document_insights', sa.Column('llm_raw_response', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'document_insights', type_='foreignkey')
    op.create_foreign_key('document_insights_document_id_fkey', 'document_insights', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('ix_document_insights_id'), table_name='document_insights')
    op.alter_column('document_insights', 'recommendations',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('document_insights', 'risks',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.drop_column('document_insights', 'raw_data')
    # ### end Alembic commands ###
